//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMe.WcfClient.WcfServices.Review {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServices.Review.IReviewDal")]
    public interface IReviewDal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDal/Create", ReplyAction="http://tempuri.org/IReviewDal/CreateResponse")]
        HireMe.DataAccess.ReviewDto Create();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDal/Get", ReplyAction="http://tempuri.org/IReviewDal/GetResponse")]
        HireMe.DataAccess.ReviewDto Get(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDal/GetAll", ReplyAction="http://tempuri.org/IReviewDal/GetAllResponse")]
        HireMe.DataAccess.ReviewDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDal/Update", ReplyAction="http://tempuri.org/IReviewDal/UpdateResponse")]
        HireMe.DataAccess.ReviewDto Update(HireMe.DataAccess.ReviewDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewDal/Delete", ReplyAction="http://tempuri.org/IReviewDal/DeleteResponse")]
        void Delete(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReviewDalChannel : HireMe.WcfClient.WcfServices.Review.IReviewDal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReviewDalClient : System.ServiceModel.ClientBase<HireMe.WcfClient.WcfServices.Review.IReviewDal>, HireMe.WcfClient.WcfServices.Review.IReviewDal {
        
        public ReviewDalClient() {
        }
        
        public ReviewDalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReviewDalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewDalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewDalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HireMe.DataAccess.ReviewDto Create() {
            return base.Channel.Create();
        }
        
        public HireMe.DataAccess.ReviewDto Get(System.Guid id) {
            return base.Channel.Get(id);
        }
        
        public HireMe.DataAccess.ReviewDto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HireMe.DataAccess.ReviewDto Update(HireMe.DataAccess.ReviewDto dto) {
            return base.Channel.Update(dto);
        }
        
        public void Delete(System.Guid id) {
            base.Channel.Delete(id);
        }
    }
}
