//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMe.WcfClient.WcfServices.Customer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServices.Customer.ICustomerDal")]
    public interface ICustomerDal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDal/Create", ReplyAction="http://tempuri.org/ICustomerDal/CreateResponse")]
        HireMe.DataAccess.CustomerDto Create();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDal/Get", ReplyAction="http://tempuri.org/ICustomerDal/GetResponse")]
        HireMe.DataAccess.CustomerDto Get(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDal/GetAll", ReplyAction="http://tempuri.org/ICustomerDal/GetAllResponse")]
        HireMe.DataAccess.CustomerDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDal/Update", ReplyAction="http://tempuri.org/ICustomerDal/UpdateResponse")]
        HireMe.DataAccess.CustomerDto Update(HireMe.DataAccess.CustomerDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDal/Delete", ReplyAction="http://tempuri.org/ICustomerDal/DeleteResponse")]
        void Delete(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerDalChannel : HireMe.WcfClient.WcfServices.Customer.ICustomerDal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerDalClient : System.ServiceModel.ClientBase<HireMe.WcfClient.WcfServices.Customer.ICustomerDal>, HireMe.WcfClient.WcfServices.Customer.ICustomerDal {
        
        public CustomerDalClient() {
        }
        
        public CustomerDalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerDalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerDalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerDalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HireMe.DataAccess.CustomerDto Create() {
            return base.Channel.Create();
        }
        
        public HireMe.DataAccess.CustomerDto Get(System.Guid id) {
            return base.Channel.Get(id);
        }
        
        public HireMe.DataAccess.CustomerDto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HireMe.DataAccess.CustomerDto Update(HireMe.DataAccess.CustomerDto dto) {
            return base.Channel.Update(dto);
        }
        
        public void Delete(System.Guid id) {
            base.Channel.Delete(id);
        }
    }
}
